#!/bin/bash

sudo mv uEnv.txt /boot/uEnv.txt
sudo mv interfaces /etc/network/interfaces
cd /opt/scripts/tools/
git pull
sudo ./grow_partition.sh
sudo mkdir -p /mnt/WinPC
sudo apt-get update
sudo apt-get install -y smbclient
sudo apt-get install cifs-utils
sudo apt-get install leafpad
sudo apt-get install -y pcmanfm