#!/bin/bash

sudo mv uEnv.txt /boot/uEnv.txt
sudo mv interfaces /etc/network/interfaces

sudo mkdir -p /mnt/WinPC
sudo apt-get update
sudo apt-get install -y smbclient
sudo apt-get install cifs-utils
sudo apt-get install leafpad
sudo apt-get install -y pcmanfm

mkdir -p ~/machinekit/configs/ARM.BeagleBone.Xylotex
mkdir -p ~/machinekit/nc_files

cp -r /usr/share/linuxcnc/examples/sample-configs/ARM/BeagleBone/Xylotex/setup.sh ~/machinekit/configs/ARM.BeagleBone.Xylotex
cp -r * ~/machinekit/configs/ARM.BeagleBone.Xylotex
cp -r /usr/share/linuxcnc/examples/* ~/machinekit/nc_files

sudo cp axis_x /usr/bin/axis_x
sudo chmod a+x /usr/bin/axis_x

sudo cp axis_x.tcl /usr/share/axis/tcl/axis_x.tcl

cd /opt/scripts/tools/
git pull
sudo ./grow_partition.sh
echo REBOOT by typing: sudo reboot
